typography_spectrum: 0.6423549018800259
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7071417944971472
  lightness: 0.7128976339008659
  saturation: 0.8475541032385081
  rhythmicContrast: 0.4696509726345539
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21314302762039006
analytics:
  google: null
  facebook: null
  twitter: null
name: New York Sex Therapists
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: MyTherapist New York
purpose: []
